version: '2'
services:
  portal-mongo:
      image: mongo:latest
      container_name: "portal-mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/logs
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27017
      networks:
        - portal-network

  portal-backend:
      image: portal-backend:latest
      container_name: "portal-backend"
      depends_on:
        - portal-mongo
      ports:
        - 8000:8000
      networks:
        - portal-network
networks:
  portal-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/26
          gateway: 192.168.2.1
